source/lib/state_representation/include/state_representation/Robot/JointState.hpp

This PR add the `set_velocities`, `set_accelerations` and `set_torques` functions with `std::vector<double>` as input parameter. `set_positions` was already implemented so this effectively just add the missing functions.

Add missing setter from std vector

---

source/lib/dynamical_systems/include/dynamical_systems/Circular.hpp
source/lib/dynamical_systems/src/Circular.cpp

* Add member normal_gain_ to Circular DS class
* Rename member gain_ to planar_gain_
* Distinguish between planar and normal gain in the main
evaluation: normal gain applies to the difference in local
Z axis, while planar gain is in the local XY.
* Update setters and getters (set_gain function sets both
gain members to the same value, so default  behaviour is unaffected)
* Reformat and fix some typos in docstrings
-- I would like this feature because I might want to treat normal gain differently than planar gain, for example to have a kind of "cylinder" response. In particular I want to control vertical gain externally (for adapting contact force), while tracking the planar gain much more closely.
Tip: hide whitespace changes when reviewing the changes

Normal gain member for CircleDS

---

source/packages/modulo_core/src/Communication/MessagePassing/ReadStateConversion.cpp

* Recent removal of the Jacobian::set_rows and ::set_cols
methods from the control_libraries development stream means
that these lines have been removed. Now, if the passed
Jacobian does not have the right size, it will
throw an IncompatibleSizeException.
If it's undesirable to throw an exception within the read message, the alternative is to construct and swap a new Jacobian object with the corresponding robot name from the original state and everything else from the message state. I don't know what you prefer here - lightweight code that can raise exceptions, or slightly heavier code that is exception safe. I feel like the former is preferable in the message layer.

Fix Jacobian setters in ReadStateConversion

---

source/packages/modulo_core/include/modulo_core/Cell.hpp

For the `state_machine` refactor I needed publisher of predicates to be always active, i.e. starting publish when the node is configured and not only activated. This functionality was already existing for `tf_broadcaster` that actually are `publishers` under the hood. So what was missing was simply to pass the same boolean in `publisher` and `subscriptions` to enable this functionality.

Add the always_active boolean to publishers and subscribers

---

source/packages/modulo_core/src/Cell.cpp

The `periodic_call` functions are defined in the same way than the normal `step` function with a `run` function that loop while the node is `configured`. This effectively means that the `add_periodic_call` function needs be put in the `on_configure` function of the node. Problem was that the`on_configure` function of the derived nodes is called prior the setting of the `configured_` boolean. This means that the `run_periodic_call` function was exiting as soon as it was added. Simple solution is to set the `configured_` boolean prior the `on_configure` call. In case the node fails to configure anyway, the reset function is called which terminates all threads and reset all handlers of threads and publishers. So I think it is actually rather safe to do like this.

Fix periodic call exiting before configure

---

Dockerfile
source/packages/modulo_core/include/modulo_core/Cell.hpp
source/packages/modulo_core/src/Cell.cpp

When discussing with @eeberhard I realized that using thread in the `Cell` class was actually breaking ros2 design that rely on a specific pattern called wall timer. This is used to add periodic publishing functions, but in fact it is also made to add any type of periodic call and works fine to handle the `step` function.
I have therefore removed all threads to switch to this wall timer and everything behave smoothly. I initially thought that those timer functions would not be called when the node is `deactivated` but that is not the case. In a sense this is actually good for us we can encapsulate the callback functions in another function that checks for node activation and also handle the mutex guard. However, it also means that this will probably not solve the throttling issue when too …

Use wall timer instead of threads

---

source/packages/modulo_core/include/modulo_core/Cell.hpp
source/packages/modulo_core/include/modulo_core/Communication/CommunicationHandler.hpp
source/packages/modulo_core/include/modulo_core/Communication/MessagePassing/MessagePassingHandler.hpp
source/packages/modulo_core/include/modulo_core/Communication/MessagePassing/PublisherHandler.hpp
source/packages/modulo_core/include/modulo_core/Communication/MessagePassing/SubscriptionHandler.hpp
source/packages/modulo_core/include/modulo_core/Communication/MessagePassing/TransformBroadcasterHandler.hpp
source/packages/modulo_core/include/modulo_core/Communication/MessagePassing/TransformListenerHandler.hpp
source/packages/modulo_core/include/modulo_core/Communication/ServiceClient/ClientHandler.hpp
source/packages/modulo_core/src/Cell.cpp
source/packages/modulo_core/src/Communication/CommunicationHandler.cpp
source/packages/modulo_core/src/Communication/MessagePassing/MessagePassingHandler.cpp
source/packages/modulo_core/src/Communication/MessagePassing/TransformBroadcasterHandler.cpp

Nothing like a good old PR that removes lines of code. As the title says, callbacks from `wall_timer` are thread safe, even when using `MultiThreadedExecutor` (cf https://answers.ros.org/question/316539/are-callbacks-of-the-same-node-called-sequentally-in-multithreadexecutor/). Thanks to PR #14, all threads have been removed rendering the use of mutexes obsolete.

Remove mutexes that are not needed when using callbacks

---

.gitignore
source/packages/modulo_core/include/modulo_core/Cell.hpp
source/packages/modulo_core/include/modulo_core/Utilities/utilities.hpp
source/packages/modulo_core/src/Cell.cpp

* Add constructor declaration and
definition for Cell to take a
NodeOptions structure and parse
the name and period. This is
so that the Cell can be configured
as a component.
* Add utilities header to make parsing
NodeOptions more convenient. This utility
can be used by derived classes outside
of modulo core.

Add NodeOptions constructor to Cell

---

.github/workflows/build-push.yml
Dockerfile

The CI was failing with the new libproto copy command:
> When using COPY with more than one source file, the destination must be a directory and end with a /
I added a temporary CI build on PR synchronise to test this. I will remove it once the image build.

Fix docker COPY in CI

---

source/modulo_core/include/modulo_core/Component.hpp
source/modulo_core/src/Component.cpp

* Add NodeOptions constructor to Component
class to make components loadable through
the component manager. This uses the base
Cell constructor to parse the NodeOptions.

Component NodeOptions constructor

---

source/modulo_core/include/modulo_core/Cell.hpp
source/modulo_core/include/modulo_core/Component.hpp
source/modulo_core/src/Cell.cpp
source/modulo_core/src/Component.cpp

The whole predicate publishing was only happening when the node was actually activated. This fixes this issues by changing the scope of `always_activated` communication handlers. It also introduces the concept of `daemons` function calls that are always happening in the background even if the node is not configured (e.g. `update_parameters` function call.

Fix the predicate publishing that was only happening at activation

---

Dockerfile.development
Dockerfile.production
build.sh
source/modulo_core/src/Cell.cpp

Due to the latest push in `control_libraries` that removes `from_std_vector`, `modulo` was in a broken state. This PR fixes it by using `set_data`. It also introduces a new Dockerfile structure that allow to create a remote development server even if modulo is not compiling. This might need to change the CI handles the images.

Fix the removed from_std_vector

---

Dockerfile.development

This PR changes the name of `control_libraries` to `control-libraries`.

Update to control-libraries renaming

---

Dockerfile.development

Now that the image combining ros2 and control-libraries has been pushed, it can be used as a base for modulo

Use ros2-control-libraries image

---

.github/workflows/build-push.yml
Dockerfile.production

Due to the new Dockerfiles, the CI is broken. I needed to introduce an argument BASE_IMAGE for the production image such that the it can be based on a random name in the CI (the name there is `dev-image`)

Fix CI with two Dockerfiles

---

build.sh

The current building process for the development and production image was not very convenient as it required to modify the script in case you wanted to build the production image. This PR introduces the `-p|--production` option to the script to build the production image. Note that it also build the development one first and uses the `-r` option if provided. This PR also correct the pulled image which was not changed to `ros2-contol-libraries`

Improve the script to build also the production image

---

source/modulo_core/include/modulo_core/Component.hpp
source/modulo_core/src/Cell.cpp
source/modulo_core/src/Component.cpp

This PR includes proper verification when shutting down the node both from lifecycle transition call and actual node destructor. It verifies in which state the node currently is and apply the transitions until it reaches the `FINALIZED` state.
Note that due to the implementation of the transitions in `ros2` it is actually not possible to use the `trigger_transition` function (shutting down transition has its proper logic from which you can't call deactivate and such; on destruction, the node can't publish its transition). Thus, we rely on our own `on_x` calls, for which we don't check the current state the node is.
This can be tested by simply loading one of the example and try combinations of `ctrl + c` / lifecycle calls.

Refactor the shutdown logic

---

build-server.sh

This PR adopts the paradigm where the default layer should be production not development. This way you can directly serve a production server or a development one.
One thing to note is that serving a development server, then a production one will generate an error as the two images do not have the same name. Thus, docker will complain that the port is already use.

Modify build script for production by default

---

source/modulo_core/include/modulo_core/communication/EncodedState.hpp

This PR is complementary to https://github.com/aica-technology/dynamic-components/pull/20. With this, both `python` and `c++` versions of the encode state transfer are consistent.
This has been tested on the examples. Note that the examples have trouble running at the moment due to the changes made on the `Parameters`. Thus, this need to be the next fix.

Change the underlying message type to UInt8MultiArray

---

source/modulo_core/include/modulo_core/Component.hpp

In `Component`, the `step` function was overwritten to be declared as pure virtual which does not really make sense. This PR simply removes it from the header.

Remove the pure virtual step function

---

source/modulo_core/include/modulo_core/Cell.hpp
source/modulo_core/include/modulo_core/communication/message_passing/TransformListenerHandler.hpp
source/modulo_new_core/include/modulo_new_core/communication/MessagePair.hpp
source/modulo_new_core/include/modulo_new_core/communication/MessagePairInterface.hpp
source/modulo_new_core/include/modulo_new_core/communication/MessageType.hpp
source/modulo_new_core/include/modulo_new_core/exceptions/InvalidMessagePairCastException.hpp
source/modulo_new_core/include/modulo_new_core/exceptions/InvalidPointerException.hpp
source/modulo_new_core/include/modulo_new_core/translators/ReadStateConversion.hpp
source/modulo_new_core/include/modulo_new_core/translators/WriteStateConversion.hpp
source/modulo_new_core/package.xml
source/modulo_new_core/src/communication/MessagePair.cpp
source/modulo_new_core/src/translators/ReadStateConversion.cpp
source/modulo_new_core/src/translators/WriteStateConversion.cpp
source/modulo_new_core/test/cpp_tests/communication/test_message_pair.cpp
source/modulo_new_core/test/cpp_tests/translators/test_translators.cpp

In order to use the translator functions in `MessagePair::write_message()`, I had to implement those translations first, which is what I'm doing here.
Additionally, I added two exceptions to handle pointer casting better.
A point that we can maybe discuss if if the MessagePair should hold it's own clock (initialized from the constructor), or if the `write_message` should take an argument which would be either time or clock
@buschbapti

Use translators in MessagePair

---

build-server.sh
source/modulo_core/src/Cell.cpp
source/modulo_core/src/Recorder.cpp

Quick fix so we can keep modulo_core alive on the refactor branch
The base image tag in the build script should go back to `galactic-devel` once merged and rebuilt

Fix modulo_core after StateType refactor

---

source/modulo_components/CMakeLists.txt
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/test/python/conftest.py
source/modulo_components/test/python/test_component_interface.py

This PR introduces the `ComponentInterface` class in python with testing of the predicate interface.

Add the base ComponentInterface class in python

---

source/modulo_new_core/CMakeLists.txt
source/modulo_new_core/include/modulo_new_core/communication/MessagePair.hpp
source/modulo_new_core/include/modulo_new_core/communication/MessagePairInterface.hpp
source/modulo_new_core/src/communication/MessagePair.cpp
source/modulo_new_core/test/cpp_tests/communication/test_message_pair.cpp

Here I specialize all available MessagePairs. As a consequence, I can remove the `MessageType` argument from the constructor. Additionally, I already add the `read_message` / `read` methods for the future subscription handler.
Note that the specializations for the `EncodedState` read/write are marked as TODOs because I'm waiting for other PRs to resolve those.

Specialize all available MessagePairs and add read capability

---

source/modulo_new_core/include/modulo_new_core/communication/PublisherHandler.hpp
source/modulo_new_core/include/modulo_new_core/communication/PublisherInterface.hpp
source/modulo_new_core/src/communication/PublisherInterface.cpp
source/modulo_new_core/test/cpp_tests/communication/test_publisher_handler.cpp

Another small increment towards our new components.
This PR adds the implementation of the previously defined `publish` method for the `PublisherInterface`. Due to the fact that this method doesn't have arguments or templates, two switch cases are needed to get and publish the correct message with the correct publisher type.

Implementation of publisher interface

---

source/modulo_new_core/CMakeLists.txt
source/modulo_new_core/include/modulo_new_core/translators/parameter_translators.hpp
source/modulo_new_core/src/translators/parameter_translators.cpp
source/modulo_new_core/test/cpp_tests/translators/parameters/test_parameter_readers.cpp

* Implement parameter translators to read and write between ROS parameters and state representation ParameterInterface pointers
* Add parameterized test fixtures to test reading and rewriting a ROS parameter object
This is a work in progress on parameter logic in the new component, but the first stage is worth reviewing now. The idea is to be able to go back and forth between ROS parameters and ParameterInterface, in some cases using json encoding to store State parameters in ROS parameter strings. I haven't implemented tests for the `read_parameter` which takes an existing Parameter by reference.
@buschbapti @domire8

Add parameter translators

---

source/modulo_new_core/include/modulo_new_core/communication/MessagePair.hpp
source/modulo_new_core/include/modulo_new_core/translators/message_writers.hpp
source/modulo_new_core/src/translators/message_writers.cpp
source/modulo_new_core/test/cpp_tests/communication/test_message_pair.cpp
source/modulo_new_core/test/cpp_tests/communication/test_publisher_handler.cpp
source/modulo_new_core/test/cpp_tests/translators/test_messages.cpp

Now that we have the most recent changes from control libraries (encode/decode shared pointer of State), we can use that in the translators and message pair to read and write the encoded state pair (and also publish it with the PublisherInteface)
@buschbapti

Support write/read for MessagePair<EncodedState, State>

---

source/modulo_components/CMakeLists.txt
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/include/modulo_components/utilities/utilities.hpp
source/modulo_components/test/cpp/test_component_interface.cpp
source/modulo_components/test/cpp/test_component_interface_parameters.cpp

* Implement add_ and get_ methods for component parameters, using
the modulo parameter translators.
* Link clproto in CMakeLists because of parameter translators
* Add tests for component parameter behaviour
This PR follows #57 and applies the translation logic in the ComponentInterface.
@buschbapti @domire8

Component Parameters

---

source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/test/cpp/test_component_interface_parameters.cpp

I kept this separate from #58 to prevent it from being too large. Mainly, I want to encourage parameter descriptions in C++. I also added a helper function to set the parameter value (for when you add a parameter by name and value and don't hold a ParameterInterface as a class property that you can modify directly). 
Finally it became clear that the TF broadcaster and listener would not work as parameters. The idea is that derived classes can selectively enable or disable these. Parameters are intended to be a user-facing API over the ROS interface, while derived classes should use protected functions or properties as the "API" to base classes. In addition, because base class construction happens before derived class construction, the only way for a derived class to update these …

Component parameter description and improvements

---

source/modulo_components/src/ComponentInterface.cpp
source/modulo_new_core/modulo_new_core/translators/parameter_translators.py
source/modulo_new_core/test/python_tests/conftest.py
source/modulo_new_core/test/python_tests/translators/test_messages.py
source/modulo_new_core/test/python_tests/translators/test_parameters.py

Sadly there are no switch cases with our python version, so a lot of if conditions. I decided to list all possible cases to be precise and to not implicitely include possible new supported parameter types. All in all, the cpp behavior is quite well replicated, with `read_parameter` and `read_parameter_const`. The replicated tests pass exactly in the same way :+1:

Parameter translators in python

---

Dockerfile
source/modulo_components/include/modulo_components/Component.hpp
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/include/modulo_components/LifecycleComponent.hpp
source/modulo_components/include/modulo_components/exceptions/SignalAlreadyExistsException.hpp
source/modulo_components/test/cpp/test_component_interface.cpp
source/modulo_components/test/cpp/test_component_interface_parameters.cpp
source/modulo_new_core/CMakeLists.txt
source/modulo_new_core/include/modulo_new_core/communication/SubscriptionHandler.hpp
source/modulo_new_core/include/modulo_new_core/communication/SubscriptionInterface.hpp
source/modulo_new_core/src/communication/SubscriptionHandler.cpp
source/modulo_new_core/src/communication/SubscriptionInterface.cpp
source/modulo_new_core/test/cpp_tests/communication/test_subscription_handler.cpp

Quite a big step IMO, I added a SubscriptionInterface and SubscriptionHandler to `modulo_new_core` in order to be able to create and store ROS subscriptions in non-templated pointers.
Subscriptions can be added in two ways, see `add_input` in ComponentInterface:
- Either by providing a shared pointer to a variable, which creates a message pair to read the state in the subscription callback
- or by providing a callback function
I would like to update the tests so they run on both the LifecycleNode and the Node but that can be done in a subsequent PR

Subscription handler/interface and add_input

---

source/modulo_new_core/include/modulo_new_core/translators/message_readers.hpp
source/modulo_new_core/test/cpp_tests/communication/test_communication.cpp
source/modulo_new_core/test/cpp_tests/communication/test_message_pair.cpp
source/modulo_new_core/test/cpp_tests/communication/test_publisher_handler.cpp
source/modulo_new_core/test/cpp_tests/communication/test_subscription_handler.cpp
source/modulo_new_core/test/cpp_tests/translators/parameters/test_parameter_translators.cpp

Slightly over the limit of 250 lines due to another big switch case for the reading of a shared pointer of state.
The main change is the test coverage of the Publisher and Subscriber interface with 2 nodes communicating and checking that the messages have been received for all supported message types

Improve test coverage in modulo new core

---

source/modulo_components/CMakeLists.txt
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/src/ComponentInterface.cpp
source/modulo_components/test/cpp/include/test_modulo_components/component_public_interfaces.hpp
source/modulo_components/test/cpp/test_component.cpp
source/modulo_components/test/cpp/test_component_interface.cpp
source/modulo_components/test/cpp/test_component_interface_parameters.cpp
source/modulo_components/test/cpp/test_lifecycle_component.cpp

With this PR, I'm forward declaring our friend test classes such that we can use `TYPED_TEST` with `NodeT` template test classes to test both lifecycle and normal component interface.
A consequence of this is that I needed to add `this->` in the parameter tests, which results in a big diff.
Also added a few more test cases

Improve components tests

---

.github/actions/build-test-galactic/Dockerfile
.github/actions/build-test-galactic/action.yml
.github/actions/build-test-galactic/entrypoint.sh
.github/workflows/build-test.yml
source/modulo_components/CMakeLists.txt
source/modulo_new_core/CMakeLists.txt

Now that the refactored packages have meaningful and passing tests, we can iterate and close on this refactor more effectively if the CI informs us of any issues with the build or test stages.
I used a custom [docker action](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions) to run a build and test script. Unfortunately with the limitations of the action syntax I am stuck with hard-coding the base image. In other repos we use a different build-push action which supports build args, but for now I didn't want to spend too long on this feature. Mainly something to help us move on the PRs with more confidence.
@domire8 @buschbapti

Build and test packages in CI

---

build-server.sh
source/modulo_components/include/modulo_components/Component.hpp
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/modulo_components/exceptions/component_exceptions.py
source/modulo_components/test/cpp/include/test_modulo_components/component_public_interfaces.hpp
source/modulo_components/test/cpp/test_component_interface.cpp
source/modulo_components/test/python/test_component_interface.py
source/modulo_new_core/modulo_new_core/translators/message_writers.py
source/modulo_new_core/test/python_tests/translators/test_messages.py

The `add_tf_xxx` and send/lookup transform was already here but not tested and exceptions not caught according to the guidelines. I'm fixing this here and doing the same in python, where it was not implemented so far.
I changed from tf broadcaster to a publisher for the `tf` topic, because I was not able to create a tf broadcaster (probably due to private inheritance)
Review by commit

TF improvements

---

source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_core/include/modulo_core/communication/message_passing/PublisherHandler.hpp
source/modulo_core/include/modulo_core/communication/message_passing/SubscriptionHandler.hpp
source/modulo_core/src/communication/message_passing/TransformListenerHandler.cpp
source/modulo_new_core/include/modulo_new_core/communication/MessagePair.hpp
source/modulo_new_core/include/modulo_new_core/translators/message_readers.hpp
source/modulo_new_core/include/modulo_new_core/translators/message_writers.hpp
source/modulo_new_core/modulo_new_core/translators/message_readers.py
source/modulo_new_core/modulo_new_core/translators/message_writers.py
source/modulo_new_core/src/translators/message_readers.cpp
source/modulo_new_core/src/translators/message_writers.cpp
source/modulo_new_core/test/cpp_tests/communication/test_communication.cpp
source/modulo_new_core/test/cpp_tests/communication/test_message_pair.cpp
source/modulo_new_core/test/cpp_tests/communication/test_publisher_handler.cpp
source/modulo_new_core/test/cpp_tests/communication/test_subscription_handler.cpp
source/modulo_new_core/test/cpp_tests/translators/test_messages.cpp
source/modulo_new_core/test/python_tests/translators/test_messages.py

Looks like a big change but I just refactored all the occurrences of 'msg' to 'message' because I like it better. Will take an executive decision and merge without review if the tests pass as there was nothing changed with the logic of the code

Refactor 'msg' to 'message' for readability

---

source/modulo_new_core/include/modulo_new_core/communication/MessagePair.hpp
source/modulo_new_core/src/communication/MessagePair.cpp
source/modulo_new_core/test/cpp_tests/communication/test_communication.cpp

There was a rather big issue in the current MessagePair implementation: Due to the fact that all 6 `make_shared_message_pair<MsgT, Data>` were specialized in the source file, it was not possible to create message pairs with
```
make_shared_message_pair<state_representation::State, EncodedState>(std::shared_ptr<CartesianTwist> data)
```
(i.e. you could only make a pair if the input data pointer was also a `State` and not one of its derived classes). This is fixed now by keeping one `make_shared_message_pair` templated (props to @buschbapti the templating guru).
Note that without the `inline` keywords in the header, this solution wouldn't work (just for future reference, the `inline` keyword can actually be really important)

Fix MessagePair to enable creating from any SR type

---

source/modulo_components/modulo_components/component_interface.py

After testing with some base components, I had to learn the hard way that after some operations with state representation types, e.g. 
```
collision = target_tf.get_position()[2] - center_tf.get_position()[2] < 0
self._in_bounds = not collision if self._flip_normal.get_value() else collision
```
the resulting variable could be of type `numpy.bool` or `numpy.bool_` and I think we should catch those cases in the component interface and convert to builtin bool.

Make sure predicate is a bool

---

source/modulo_components/include/modulo_components/Component.hpp
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/include/modulo_components/LifecycleComponent.hpp
source/modulo_components/include/modulo_components/utilities/utilities.hpp
source/modulo_components/src/LifecycleComponent.cpp
source/modulo_components/test/cpp/include/test_modulo_components/component_public_interfaces.hpp
source/modulo_components/test/cpp/test_component_interface.cpp

One of my initial tests showed that it is not possible to inherit with `private` from `NodeT` and we were already thinking of switching back to `public` so here it is. As a consequence, we can also switch back to a `TransformBroadcaster` and create `rclcpp::Publisher` explicitly for all predicate publishers. And finally, we can use lambda functions with `get_current_state` in the lifecycle components to get the current state for all predicates.
An important TODO here will be to hide all non necessary methods from ROS in the components

Inherit from NodeT with public keyword

---

source/modulo_components/include/modulo_components/Component.hpp
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/include/modulo_components/LifecycleComponent.hpp
source/modulo_components/modulo_components/component.py
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/modulo_components/exceptions/component_exceptions.py
source/modulo_components/modulo_components/utilities/utilities.py
source/modulo_components/src/LifecycleComponent.cpp
source/modulo_components/test/python/test_component.py
source/modulo_components/test/python/test_component_interface.py
source/modulo_new_core/modulo_new_core/translators/message_readers.py
source/modulo_new_core/modulo_new_core/translators/message_writers.py
source/modulo_new_core/test/python_tests/translators/test_messages.py

Let's try this again. This PR adds the input and output signals to the python component interface. As with the parameters, it takes a name of a class attribute that should be used to publish messages and receive messages.

Add inputs and outputs to python component interface

---

.github/actions/build-test-galactic/Dockerfile
build-server.sh
source/modulo_components/CMakeLists.txt
source/modulo_new_core/CMakeLists.txt
source/modulo_new_core/modulo_new_core/translators/parameter_translators.py
source/modulo_new_core/test/python_tests/conftest.py
source/modulo_new_core/test/python_tests/translators/test_parameters.py

Now that the default value of empty parameters was fixed in control libraries PR [#298](https://github.com/epfl-lasa/control-libraries/pull/298), I can use the `galactic-devel` image of ros2-control-libraries and make sure that the translation between state representation parameters and ROS parameters works correctly. What happened before was:
- an empty state rep Parameter of type double, int, etc would have a non-default value (for example 1 for double).
- an empty state rep Parameter of type XXX_ARRAY would have ROS parameter type BYTE_ARRAY
Both of these bugs are fixed now and you get the correct parameter type in ROS with correct default value.

Translation of empty parameters

---

source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/modulo_components/lifecycle_component.py
source/modulo_components/src/LifecycleComponent.cpp

Last but not least, the Python LifecycleComponent. It's more or less a copy of the old component from dynamic components except that I added the cleanup transition and I publish the predicates based on the current state of the component with lambda functions.
Has already been tested and works as expected. I'm not sure if we need to do better with the transitions and even add on shutdown but that could also wait until the humble upgrade.

Add lifecycle component in Python

---

source/modulo_components/include/modulo_components/LifecycleComponent.hpp
source/modulo_components/src/LifecycleComponent.cpp

Rename the transition handlers and callbacks according to the new design and as it already is in Python

Rename transition handlers and callbacks

---

.github/workflows/build-push.yml

We have an action that builds and pushes a modulo image if develop or main have new commits but the action does not differentiate between main and develop, hence on push on develop we'll always have a workflow that fails until main is building properly again. I propose to remove develop from that action, also because we don't need to rebuild an image that we are never actually using on each push to develop.

Don't run image build on push on develop

---

source/modulo_components/include/modulo_components/Component.hpp
source/modulo_components/modulo_components/component.py
source/modulo_components/src/Component.cpp
source/modulo_components/test/cpp/include/test_modulo_components/component_public_interfaces.hpp
source/modulo_components/test/cpp/test_component.cpp

To be fair, we should even think about removing that option entirely (especially in C++), because we could not think of a component that would want to start a thread on execution and I think it's even really dangerous because we are calling a virtual function from the constructor. In Python it's not such a big problem

Don't start execute thread on construction

---

source/modulo_components/include/modulo_components/LifecycleComponent.hpp
source/modulo_components/modulo_components/lifecycle_component.py
source/modulo_components/src/LifecycleComponent.cpp

This change allows lifecycle components to add outputs on configure and I think it's better this way anyway, that we first do what the user wants and then what we want to do in the background.

Execute user transition callback first

---

source/modulo_components/CMakeLists.txt
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/test/cpp/include/test_modulo_components/component_public_interfaces.hpp
source/modulo_components/test/cpp/test_component_interface_empty_parameters.cpp
source/modulo_components/test/cpp/test_component_interface_parameters.cpp
source/modulo_components/test/python/test_component_interface_empty_parameters.py
source/modulo_components/test/python/test_component_interface_parameters.py
source/modulo_core/src/translators/parameter_translators.cpp

Okay now I think we're getting somewhere..There are a few changes to the logic here but most of the lines come from the tests
- Add parameter now throws an exception if the parameter could not be added for some reason (translation failed or validation failed). Note that upon declaration of a `NOT_SET` parameter in C++, the set parameter callback is not called, hence we need to validate that parameter explicitly in the `add_parameter`.
- Even though, empty parameters are declared with `dynamic_typing=true`, it's not possible to change the parameter type once the parameter was set because `read_parameter_const` will throw an exception and the callback will return false.
- Along the other changes, I added the `read_only` field for python ROS parameters and it works as in C++ (tested)
Also …

Handle empty parameters in ComponentInterface

---

source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/test/cpp/include/test_modulo_components/component_public_interfaces.hpp
source/modulo_components/test/cpp/test_component_interface.cpp
source/modulo_components/test/python/test_component_interface.py

Two minor features that we discussed over the past days:
- Send a predicate value immediately after its set, on top of the periodic publishing
- Add a trigger that is essentially a predicate that is always false except when its triggered it will be evaluated to true exactly once.

Add trigger and send predicate on set

---

.github/actions/build-test-galactic/entrypoint.sh
Dockerfile
source/modulo_component_interfaces/CMakeLists.txt
source/modulo_component_interfaces/package.xml
source/modulo_component_interfaces/srv/EmptyTrigger.srv
source/modulo_component_interfaces/srv/StringTrigger.srv
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py
source/modulo_components/package.xml
source/modulo_components/test/cpp/include/test_modulo_components/component_public_interfaces.hpp
source/modulo_components/test/cpp/test_component_interface.cpp
source/modulo_components/test/python/test_component_interface.py

For components to have simple services that can trigger certain behaviours, it is necessary to define some service messages. A new package defines these component interfaces.
The new component add_service methods allow simple creation of these services with registered callbacks, either taking no arguments or a single string argument. They return a status and optional message. This should allow flexible and general usage while limiting the number of specific service types that need to be supported.
Still some TODOs for documentation and better tests but I think the general idea is ready for review

Component services

---

source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/modulo_components/component_interface.py

* Formatting fixes in log lines
I missed something in #103 - though I tested that the services were created, I forgot about the namespace. The intended syntax is that some `service_endpoint` on component `foo` becomes available on the topic `/foo/service_endpoint`, so that the AICA state engine ComponentInterface can automatically associate the service endpoint with the target component. While add_input provides a "default topic" option for flexible renaming or remapping, I believe services should be more static in their registered namespace. Signals can be renamed to connect components together, but services are always endpoints associated with a component, and so should be in the namespace of that component.
This has been tested and works as intended.

Create service under local namespace

---

source/modulo_components/include/modulo_components/Component.hpp
source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/include/modulo_components/LifecycleComponent.hpp
source/modulo_components/modulo_components/component.py
source/modulo_components/modulo_components/lifecycle_component.py
source/modulo_components/src/LifecycleComponent.cpp
source/modulo_components/test/python/test_component_interface_empty_parameters.py
source/modulo_core/CMakeLists.txt
source/modulo_core/include/modulo_core/communication/PublisherHandler.hpp
source/modulo_core/include/modulo_core/exceptions/CoreException.hpp
source/modulo_core/include/modulo_core/exceptions/InvalidPointerCastException.hpp
source/modulo_core/include/modulo_core/exceptions/InvalidPointerException.hpp
source/modulo_core/include/modulo_core/exceptions/MessageTranslationException.hpp
source/modulo_core/include/modulo_core/exceptions/NullPointerException.hpp
source/modulo_core/include/modulo_core/exceptions/ParameterTranslationException.hpp
source/modulo_core/include/modulo_core/translators/message_readers.hpp

There were some smaller TODOs left regarding exception handling that I tried to resolve here. With the publisher handler (hopefully) only throwing CoreExceptions, we can just catch those explicitely.

Catch core and component exceptions

---

source/modulo_components/include/modulo_components/ComponentInterface.hpp
source/modulo_components/test/cpp/include/test_modulo_components/communication_components.hpp
source/modulo_components/test/cpp/include/test_modulo_components/component_public_interfaces.hpp
source/modulo_components/test/cpp/test_component_communication.cpp
source/modulo_components/test/cpp/test_component_interface.cpp
source/modulo_components/test/cpp/test_lifecycle_component_communication.cpp
source/modulo_core/include/modulo_core/communication/SubscriptionHandler.hpp
source/modulo_core/src/communication/SubscriptionHandler.cpp
source/modulo_core/test/cpp/include/test_modulo_core/communication_nodes.hpp

[Insert a user callback into SubscriptionHandler](https://github.com/epfl-lasa/modulo/commit/b64a7e0bee1a1ab320770dd4da38ed11a787299c)
* Add private class property and setter for user_callback_, a void function
* Invoke user callback within the subscription callback, after reading the message
* Move callback error handling to helper function to simplify implementation and reduce code duplication
* Allow setting user callback directly when getting the subscription callback with a function overload
* Update test to use user callback
* Adjust docstrings
[Implement user callback in component add_input](https://github.com/epfl-lasa/modulo/commit/c56fef8fc9deaabee1418ec7a52c046ffebe85b7)
* Resolve TODO by overloading add_input with a user_callback argument after the shared data pointer. This …

User-defined callback on inputs (C++)
